# Generated by Django 2.2.3 on 2019-07-28 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 28, 17, 8, 9, 179759), verbose_name='date published'),
        ),
    ]
