# Generated by Django 2.2.3 on 2019-07-28 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190728_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 28, 20, 18, 56, 990784), verbose_name='date published'),
        ),
    ]
