# Generated by Django 2.2.3 on 2019-07-28 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190728_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 28, 21, 56, 11, 906360), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='key',
            field=models.CharField(max_length=50),
        ),
    ]
